import { createClient } from "redis";
import dotenv from "dotenv";

dotenv.config();

async function main(): Promise<void> {
  const redisUrl = process.env.REDIS_URL || "redis://localhost:6379";
  const redis = createClient({ url: redisUrl });
  
  await redis.connect();
  console.log("🔗  Connected to Redis.");

  await redis.set("embeddings_ready", "true");
  console.log("✅  Set embeddings_ready=true in Redis.");
  console.log("    (The actual embeddings will be generated by sentence-transformers at FastAPI startup from the menu data fetched via /api/menu)");
  
  await redis.disconnect();
}

main()
  .catch((e) => {
    console.error("❌  Failed:", e);
    process.exit(1);
  });
